import type { DeviceSpec } from "./types";

// First three nodes match db/seeds/devices.json; the rest extend the fleet
// across the same Southern California monitoring footprint.
export const FLEET: DeviceSpec[] = [
  {
    deviceId: "edge-ca-001",
    displayName: "Los Angeles Ridge Node 1",
    region: "southern-california",
    kind: "ridge",
    lat: 34.0522,
    lon: -118.2437,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-002",
    displayName: "Angeles Forest Node 2",
    region: "southern-california",
    kind: "forest",
    lat: 34.282,
    lon: -118.175,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-003",
    displayName: "San Gabriel Wash Node 3",
    region: "southern-california",
    kind: "wash",
    lat: 34.126,
    lon: -117.865,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-004",
    displayName: "Topanga Canyon Node 4",
    region: "southern-california",
    kind: "ridge",
    lat: 34.094,
    lon: -118.601,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-005",
    displayName: "Verdugo Hills Node 5",
    region: "southern-california",
    kind: "ridge",
    lat: 34.211,
    lon: -118.286,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-006",
    displayName: "Sepulveda Basin Node 6",
    region: "southern-california",
    kind: "wash",
    lat: 34.172,
    lon: -118.482,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-007",
    displayName: "Whittier Narrows Node 7",
    region: "southern-california",
    kind: "wash",
    lat: 34.023,
    lon: -118.065,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-008",
    displayName: "Griffith Park Node 8",
    region: "southern-california",
    kind: "forest",
    lat: 34.1365,
    lon: -118.294,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-009",
    displayName: "Santa Anita Ridge Node 9",
    region: "southern-california",
    kind: "ridge",
    lat: 34.181,
    lon: -118.033,
    firmwareVersion: "0.1.0",
  },
  {
    deviceId: "edge-ca-010",
    displayName: "Malibu Creek Node 10",
    region: "southern-california",
    kind: "wash",
    lat: 34.097,
    lon: -118.731,
    firmwareVersion: "0.1.0",
  },
];
